[project]
name = "pyside6-by-example"
version = "0.1.0"
description = "PySide6 Examples"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyside6==6.8.0.2",
    "polars==1.14.0"
]
[project.gui-scripts]
csv_browser = "net.priimak.pyside6.examples.csv_browser.main"