site_name: PySide6 By Example
theme:
  name: material
  features:
    - navigation.sections

# Markdown extensions
markdown_extensions:
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences

nav:
  - "Introduction": "intro.md"
  - "Anatomy of basic app": "anatomy_of_basic_application.md"
  - "Basic app structured": "basic_app_take_2.md"
  - "CSV Browser app": "csv_browser.md"